# Generated by Django 2.0.6 on 2018-06-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bug_details',
            fields=[
                ('SLNO', models.IntegerField(primary_key=True, serialize=False)),
                ('BUGNO', models.IntegerField()),
                ('ASSIGNEE', models.CharField(max_length=8)),
                ('STATUS', models.IntegerField(max_length=3)),
                ('SUBJECT', models.CharField(max_length=240)),
                ('ENV', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'bug_details',
            },
        ),
    ]
